config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users
  get 'sessions/create'
  get 'sessions/destroy'
  get '/welcome' => "welcome#index", as: :user_root

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [] do
    resources :habits do
      member do
        post 'create_completed_day'
      end
      resources :completed_days, only: [:destroy]
    end
  end
  resources :completed_days 

end

app/models/chain.rb
class Chain < ActiveRecord::Base
  has_many :completed_days
  belongs_to :habit

  # Calculates the number of completed days in a chain
  def chain_length
    (self[:end_date] - self[:start_date]).to_i + 1
  end

end

app/helpers/chains_helper.rb
module ChainsHelper
end

app/views/chains/index.html.erb
<h1>Your Current Chain</h1>

<div>
  <%= link_to 'Log Completed Days', new_completed_day_path %>
</div>

<div>
  <table>

    <tr>
      <% @current_chain_dates.each do |date| %>
        <td bgcolor="red"> x </td>
      <% end %>
      <% @upcoming_dates.each do |date| %>
        <td bgcolor="#E0E0E0"> o </td>
      <% end %>
    </tr>
    <tr>
      <% @current_chain_dates.each do |date| %>
        <td><%= date %></td>
      <% end %>
      <% @upcoming_dates.each do |date| %>
        <td><%= date %></td>
      <% end %>
    </tr>
  </table>
</div>

<div><p>Your previous longest chain was <%= @previous_longest_chain_length %> days long.</p></div>