config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users
  get 'sessions/create'
  get 'sessions/destroy'
  get '/welcome' => "welcome#index", as: :user_root

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [] do
    resources :habits do
      member do
        post 'create_completed_day'
      end
      resources :completed_days, only: [:destroy]
    end
  end
  resources :completed_days 

end

app/models/completed_day.rb
class CompletedDay < ActiveRecord::Base
  belongs_to :chain
  belongs_to :habit
  
  validates :date, format: { with: /\d{4}-\d{2}-\d{2}/, :message => "must be in the following format: yyyy-mm-dd" }

  validates :date, presence: { message: " may not be blank" }

  validates :date, uniqueness: { scope: [:habit_id], message: "has already been logged" }

  validates :date, :timeliness => {:on_or_before => lambda { Date.current }, :type => :date, :on_or_before_message => "is in the future"}

  # For a completed day, returns date as [yyyy,mm,dd]
  def date_as_ymd_array
    [self.date.year,
        self.date.month,
        self.date.day]
  end

end

app/controllers/completed_days_controller.rb
class CompletedDaysController < ApplicationController
  
  # def index
  #   @completed_days = CompletedDay.all.sort_by(&:date)
  # end

  def new
    # @completed_days = CompletedDay.all.sort_by(&:date)
    @completed_day = CompletedDay.new
  end

  def create
    # @completed_days = CompletedDay.all.sort_by(&:date)
    @completed_day = CompletedDay.new(completed_day_params)
    if @completed_day.save
      redirect_to user_habits_path
    else
      render 'new'
    end
  end

  def destroy
    # byebug
    @completed_day = CompletedDay.find(params[:id])

    @completed_day.destroy
    redirect_to root_path
    # redirect_to edit_user_habit_path(current_user,@completed_day.habit)
  end

  private
    def completed_day_params
      params.require(:completed_day).permit(:date)
    end

        # Habit object from params
    def habit
      @habit = Habit.find(params[:id])
    end

    # Habit's completed days sorted
    def completed_days
      @completed_days = habit.completed_days_sorted
    end

end

app/helpers/completed_days_helper.rb
module CompletedDaysHelper
end

app/views/completed_days/_completed_day_to_delete.html.erb
<tr>
  <td><%= completed_day_to_delete.date %></td>
  <td><%= link_to 'Delete', user_habit_completed_day_path(current_user,habit_id = params[:id],completed_day_id = completed_day_to_delete.id),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: "btn btn-default btn-xs",
          role: "button" %></td>
</tr>

app/views/completed_days/_form.html.erb
<%= form_for @completed_day, :url => create_completed_day_user_habit_path(current_user, @habit) do |f| %>
 
  <% if @completed_day.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@completed_day.errors.count, "error") %> prohibited this date from being logged:
      </h3>
      <ul>
        <% @completed_day.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label "Add a completed day (yyyy-mm-dd):" %><br>
    <%= f.text_field :date, class: "form-control", placeholder: "yyyy-mm-dd" %>
  </div>
 
  <div class="form-group">
    <%= f.submit "Add Completed Day", class: "btn btn-default" %>
  </div>
 
<% end %>