config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users
  get 'sessions/create'
  get 'sessions/destroy'
  get '/welcome' => "welcome#index", as: :user_root

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [] do
    resources :habits do
      member do
        post 'create_completed_day'
      end
      resources :completed_days, only: [:destroy]
    end
  end
  resources :completed_days 

end

app/models/habit.rb
class Habit < ActiveRecord::Base
  has_many :completed_days
  has_many :chains
  belongs_to :user

  validates :name, presence: { message: " may not be blank" }

  validates :name, uniqueness: { message: "has already been used" }

  attr_accessor :start_date, :end_date

  # For a given habit, returns all completed days, sorted in ascending date order.
  def completed_days_sorted
    self.completed_days.where.not(date: nil).sort_by(&:date)
  end

  # For a given habit, returns an array of chains where each "chain" is a hash with the keys "start_date" and "end_date."
  def chains
    chains_enumerator = self.completed_days_sorted.slice_before { |completed_day|
      index = self.completed_days_sorted.index(completed_day)
      self.completed_days_sorted[index-1].date != completed_day.date-1.day
    }

    chains_enumerator.map { |chain| 
      chain = {:start_date => chain[0].date, :end_date => chain[-1].date}
    }
  end

  # For a given habit, returns the latest chain, meaning the one with the most recent start date.
  def latest_chain
    latest_chain = self.chains.max_by {|chain| chain[:start_date]} 
  end

  # For a given habit, returns the number of days in the latest chain.
  def latest_chain_length
    if latest_chain.nil?
      0
    else
      (self.latest_chain[:end_date] - self.latest_chain[:start_date]).to_i + 1
    end
  end

  # For a given habit, returns the longest chain, meaning the one with the most days.
  def longest_chain
    latest_chain = self.chains.max_by {|chain| chain[:end_date] - chain[:start_date]} 
  end

  # For a given habit, returns the number of days in the longest chain.
  def longest_chain_length
    if longest_chain.nil?
      0
    else
      (self.longest_chain[:end_date] - self.longest_chain[:start_date]).to_i + 1
    end
  end

  #
  def days_this_year
    self.completed_days.to_a.keep_if { |day|
      day.date.year == Time.now.year
    }.length
  end

  # For a given habit, returns habit data in the format needed for sending to javascript column chart.
  def formatted_for_column_chart
      [self.name,self.completed_days.map { |cd| cd.date_as_ymd_array}]
  end

  # For a habit collection, returns a json array of habit objects in the format needed for creating column charts in js.
  def self.formatted_for_column_chart
    jshabits_ruby = all.map { |habit|
        if !habit.chains[0].nil?
          habit.formatted_for_column_chart
        end
      }
    jshabits = jshabits_ruby.to_json
  end

  # def previous_longest_chain
  #   self.chains.where(current: FALSE).max_by{ |chain| chain.chain_length } 
  # end

  # def previous_longest_chain_length
  #   if previous_longest_chain.nil?
  #     0
  #   else
  #     self.previous_longest_chain.chain_length
  #   end
  # end

end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  def index
    current_user_habits 
    @jshabits = current_user_habits.formatted_for_column_chart
    no_chains_message
    no_habits_message
  end 

  def new
    current_user_habits 
    @habit = current_user.habits.new
  end

  def edit
    habit
    completed_days
    # byebug
    @completed_day = CompletedDay.new

  end

  def create
    current_user_habits 
    habit_params[:name].titleize!
    @habit = current_user.habits.new(habit_params)
    if @habit.save
      redirect_to user_habits_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    habit
    habit.destroy
    redirect_to user_habits_path(current_user)
  end

  def create_completed_day
    habit
    completed_days
    @completed_day = @habit.completed_days.new(completed_day_params)
    if @completed_day.save
      redirect_to user_habits_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy_completed_day
    # byebug
    habit
    completed_days
    @completed_day = CompletedDay.find(params[:id])
    @completed_day.destroy
    redirect_to edit_user_habit_path(current_user,habit)
  end

  private
    # params from new habit form
    def habit_params
      params.require(:habit).permit(:name)
    end

    # params from new completed day form
    def completed_day_params
      params.require(:completed_day).permit(:date)
    end

    # Message to display in habit panel when no completed days have been logged for the given habit.
    def no_chains_message
      @no_chains_message = "You have not logged any days yet!"
    end

    # Message to display in habits panel when no habits have been created.
    def no_habits_message
      @no_habits_message = "You're not tracking any habits yet!"
    end

    # Array of current user's habits
    def current_user_habits
      @habits = current_user.habits
    end

    # Habit object from params
    def habit
      @habit = Habit.find(params[:id])
    end

    # Habit's completed days sorted
    def completed_days
      @completed_days = habit.completed_days_sorted
    end

end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/habits/_form.html.erb
<%= form_for [current_user, @habit] do |f| %>
 
  <% if @habit.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@habit.errors.count, "error") %> prohibited this habit from being created:
      </h3>
      <ul>
        <% @habit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label "Habit Name:" %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "i.e. Meditation" %>
  </div>
 
  <div class="form-group">
    <%= f.submit "Create Habit!", class: "btn btn-default" %>
  </div>
 
<% end %>

app/views/habits/_habit.html.erb
<div class="panel panel-default" style="width:950px; margin-left:auto; margin-right:auto">
  
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to habit.name, edit_user_habit_path(current_user,habit.id) %></h3>
  </div>

  <% if !habit.chains[0].nil? %>
  
  <div class="panel-body">
    <div id=<%= habit.name.gsub(/\s/,"-") + "-timeline" %> style="height: 160px;"></div>  
  </div>

  <table class="table table-bordered">
    <tr style="width:100%">
      <td style="width:33.3%; text-align:center">
        Days This Calendar Year</br>
        <span style="font-weight: bold; font-size: 200%">
        <%= habit.days_this_year %> days</span>
      </td>
      <td style="width:33.3%; text-align:center">
        Longest Streak</br>
        <span style="font-weight: bold; font-size: 200%">
        <%= habit.longest_chain_length %> days</span>
      </td>
      <td style="width:33.3%; text-align:center">
        Current Streak</br>
        <span style="font-weight: bold; font-size: 200%">
        <%= habit.latest_chain_length %> days</span>
      </td>
    </tr>
  </table>

  <% else %>
  
  <div class="panel-body">
    <h4><%= @no_chains_message %></h4>
  </div>

  <% end %>

</div>

app/views/habits/edit.html.erb
 <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= @habit.name %> </h3>
  </div>
  <div class="panel-body">

    <%= render :partial => 'completed_days/form' %>

    <table class="table table-condensed table-striped">
      <tr>
        <th colspan="2">Completed Days</th>
      </tr>
      <%= render partial: "/completed_days/completed_day_to_delete", collection: @completed_days %>
    </table>

    <div>
      <%= link_to 'Delete This Habit', user_habit_path(current_user, @habit),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: "btn btn-default",
                  role: "button" %>
    </div>

  </div>
</div>

app/views/habits/index.html.erb
<%= javascript_tag do %>

  var habitsRaw = <%= raw @jshabits %>;
  var habits = habitsRaw.map(function(h){
    if (h==null) {
      return null;
    } else {
      var array = [h[0],h[1].map(function(c){
        date = new Date(c);
        return date;
      })];
      return array;
    };
  });

<% end %>


<div>
  <% if !@habits[0].nil? %>
    <%= render partial: "habit", collection: @habits %>
  <% else %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">My Habits</h2>
      </div>
      <div class="panel-body">
        <h4><%= @no_habits_message %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/habits/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Track a New Habit</h3>
  </div>
  <div class="panel-body">

    <%= render 'form' %>
     
    <table class="table table-condensed table-striped">
      <tr>
        <th>My Existing Habits</th>
      </tr>
     
      <% @habits.each do |habit| %>
        <tr>
          <td><%= habit.name %></td>
          <!-- <td><%# link_to 'Delete', user_habit_path(current_user,habit.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: "btn btn-default btn-xs",
                  role: "button" %></td> -->
        </tr>
      <% end %>
    </table>

  </div>
</div>