config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users
  get 'sessions/create'
  get 'sessions/destroy'
  get '/welcome' => "welcome#index", as: :user_root

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [] do
    resources :habits do
      member do
        post 'create_completed_day'
      end
      resources :completed_days, only: [:destroy]
    end
  end
  resources :completed_days 

end

app/views/layouts/_footer.html.erb
<!-- <h4 style="text-align: center; background-color: whitesmoke">Small Wins</h4> -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Small Wins</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% else %>
          <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
          <li><%= link_to 'My Habits', user_habits_path(current_user) %></li>
          <li><%= link_to 'New Habit', new_user_habit_path(current_user) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notice_and_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Habits</title>
  <%= favicon_link_tag(source='favicon.ico') %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1.1','packages':['corechart','calendar','bar']}]}"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<%= render "layouts/header" %>

  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render "layouts/notice_and_alert" %>
        <%= yield %>
      </div>
    </div>
  </div>

<%= render "layouts/footer" %>

</body>
</html>